fixtures:
  repositories:
    concat: 'https://github.com/puppetlabs/puppetlabs-concat'
    stdlib: 'https://github.com/puppetlabs/puppetlabs-stdlib'
    python: 'https://github.com/stankevich/puppet-python'
    epel: 'https://github.com/stahnma/puppet-module-epel.git'
    systemd: 'https://github.com/voxpupuli/puppet-systemd'
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
      puppet_version: ">= 6.0.0"
